# Generated by Django 6.0.7 on 2026-07-17 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('prix_par_nuit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacite', models.PositiveIntegerField(default=1)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('titre',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='appartements/')),
                ('legende', models.CharField(blank=True, max_length=150)),
                ('principale', models.BooleanField(default=False)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='apartments.appartement')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodeVacances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('libelle', models.CharField(max_length=150)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes_vacances', to='apartments.appartement')),
            ],
            options={
                'verbose_name_plural': 'périodes de vacances',
                'ordering': ('date_debut',),
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__gt', models.F('date_debut'))), name='vacances_dates_valides')],
            },
        ),
    ]
